account/urls.py
from django.urls import path
from . import views

app_name = 'account'


urlpatterns = [
    path('register/', views.UserRegisterView.as_view(), name='user_register'),
    path('login/', views.UserLoginView.as_view(), name='user_login'),
    path('logout/', views.UserLogoutView.as_view(), name='user_logout'),
    path('profile/<int:user_id>/', views.UserProfileView.as_view(), name='user_profile'),
    path('reset/', views.UserPassResetView.as_view(), name='password_reset'),
    path('reset/done/', views.UserPassResetDoneView.as_view(), name='password_reset_done'),
    path('confirm/<uidb64>/<token>/', views.UserPassResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/complete/', views.UserPassResetCompleteView.as_view(), name='password_reset_complete'),
    path('follow/<int:user_id>/', views.UserFollowView.as_view(), name='user_follow'),
    path('unfollow/<int:user_id>/', views.UserUnfollowView.as_view(), name='user_unfollow'),
    path('edit_profile/', views.EditUserProfile.as_view(), name='edit_profile'),
    path('following/<int:user_id>/', views.UserFollowingView.as_view(), name='user_following'),
    path('followers/<int:user_id>/', views.UserFollowersView.as_view(), name='user_followers'),


]

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls', namespace='home')),
    path('account/', include('account.urls', namespace='account')),

]

home/urls.py
from django.urls import path
from . import views

app_name = 'home'

urlpatterns = [
    path('', views.HomeView.as_view(), name='home_page'),
    path('post/<int:post_id>/<slug:post_slug>/', views.PostDetailView.as_view(), name='post_detail'),
    path('post/delete/<int:post_id>/', views.PostDeleteView.as_view(), name='post_delete'),
    path('post/update/<int:post_id>/', views.PostUpdateView.as_view(), name='post_update'),
    path('post/create/', views.PostCreateView.as_view(), name='post_create'),
    path('reply/<int:post_id>/<int:comment_id>/', views.CommentAddReplyView.as_view(), name='add_reply'),
    path('like/<int:post_id>/', views.PostLikeView.as_view(), name='post_like'),
    path('dislike/<int:post_id>/', views.PostDislikeView.as_view(), name='post_dislike'),

]

home/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse


class Post(models.Model):
    title = models.CharField(max_length=100)
    body = models.TextField()
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='posts')
    slug = models.SlugField()
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-created']

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('home:post_detail', args=(self.id, self.slug))

    def likes_count(self):
        return self.plikes.count()

    def user_cant_like(self, user):
        user_like = user.ulikes.filter(post=self)
        if user_like.exists():
            return True
        return False


class Comment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='ucoments')
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='pcomments')
    reply = models.ForeignKey('self', on_delete=models.CASCADE, related_name='rcomments', blank=True, null=True)
    is_reply = models.BooleanField(default=False)
    body = models.TextField(max_length=400, verbose_name='comment')
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.user} - {self.post} - {self.is_reply} - {self.created}'


class Like(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='ulikes')
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='plikes')

    def __str__(self):
        return f'{self.user} liked {self.post}'

home/forms.py
from django import forms
from .models import Post, Comment


class PostCreateUpdateForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['title', 'body']


class CommentCreateForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['body']
        widgets = {
            'body': forms.Textarea(attrs={'class': 'form-control'}),
        }


class CommentReplyForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['body']
        widgets = {
            'body': forms.Textarea(attrs={'class': 'form-control', 'cols': 20, 'rows': 4})
        }


class PostSearchForm(forms.Form):
    search = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))

home/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views import View
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib import messages
from django.utils.text import slugify
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator

from .models import Post, Comment, Like
from .forms import PostCreateUpdateForm, CommentCreateForm, CommentReplyForm, PostSearchForm


class HomeView(View):
    form_class = PostSearchForm

    def get(self, request):
        posts = Post.objects.all()
        if request.GET.get('search'):
            posts = Post.objects.filter(title__contains=request.GET.get('search'))
        return render(request, 'home/index.html', {'posts': posts, 'form': self.form_class})


class PostDetailView(View):
    form_class = CommentCreateForm
    form_class_reply = CommentReplyForm

    def setup(self, request, *args, **kwargs):
        self.post_instance = get_object_or_404(Post, pk=kwargs['post_id'], slug=kwargs['post_slug'])
        return super().setup(request, *args, **kwargs)

    def get(self, request, *args, **kwargs):
        comments = self.post_instance.pcomments.filter(is_reply=False)
        user_cant_like = False
        if request.user.is_authenticated and self.post_instance.user_cant_like(request.user):
             user_cant_like=True
        return render(request, 'home/detail.html',
                      {'post': self.post_instance,
                       'comments': comments,
                       'form': self.form_class,
                       'reply_form': self.form_class_reply,
                       'user_cant_like': user_cant_like
                       })

    @method_decorator(login_required)
    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)
        if form.is_valid():
            new_comment = form.save(commit=False)
            new_comment.user = request.user
            new_comment.post = self.post_instance
            new_comment.save()
            messages.success(request, 'You\'re comment submitted successfully', 'success')
            return redirect('home:post_detail', self.post_instance.id, self.post_instance.slug)


class PostDeleteView(LoginRequiredMixin, View):
    def get(self, request, post_id):
        post = get_object_or_404(Post, pk=post_id)
        if request.user.id == post.user.id:
            post.delete()
            messages.success(request, 'Post deleted successfully', 'success')
            return redirect('home:home_page')
        else:
            messages.error(request, 'You can\'t delete this post!', 'danger')
            return redirect('home:home_page')


class PostUpdateView(LoginRequiredMixin, View):
    form_class = PostCreateUpdateForm
    template_name = 'home/update.html'

    def setup(self, request, *args, **kwargs):
        self.post_instance = get_object_or_404(Post, pk=kwargs['post_id'])
        return super().setup(request, *args, **kwargs)

    def dispatch(self, request, *args, **kwargs):
        post = self.post_instance
        if not request.user.id == post.user.id:
            messages.error(request, 'You can\'t update this post!', 'danger')
            return redirect('home:home_page')
        return super().dispatch(request, *args, **kwargs)

    def get(self, request, *args, **kwargs):
        post = self.post_instance
        form = self.form_class(instance=post)
        return render(request, self.template_name, {'form': form})

    def post(self, request, *args, **kwargs):
        post = self.post_instance
        form = self.form_class(request.POST, instance=post)
        if form.is_valid():
            new_post = form.save(commit=False)
            new_post.slug = slugify(form.cleaned_data['title'][:30])
            new_post.save()
            messages.success(request, 'post updated successfully', 'success')
            return redirect('home:post_detail', post.id, post.slug)
        return render(request, self.template_name, {'form': form})


class PostCreateView(LoginRequiredMixin, View):
    form_class = PostCreateUpdateForm
    template_name = 'home/create.html'

    def get(self, request, *args, **kwargs):
        form = self.form_class
        return render(request, self.template_name, {'form': form})

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)
        if form.is_valid():
            new_post = form.save(commit=False)
            new_post.user = request.user
            new_post.slug = slugify(form.cleaned_data['title'][:30])
            new_post.save()
            messages.success(request, 'Post created successfully')
            return redirect('home:post_detail', new_post.id, new_post.slug)
        return render(request, self.template_name, {'form': form})


class CommentAddReplyView(LoginRequiredMixin, View):
    form_class = CommentReplyForm

    def post(self, request, post_id, comment_id):
        post = get_object_or_404(Post, pk=post_id)
        comment = get_object_or_404(Comment, pk=comment_id)
        form = self.form_class(request.POST)
        if form.is_valid():
            reply = form.save(commit=False)
            reply.user = request.user
            reply.post = post
            reply.reply = comment
            reply.is_reply = True
            reply.save()
            messages.success(request, 'You\'re replay submitted successfully', 'success')
        return redirect('home:post_detail', post.id, post.slug)


class PostLikeView(LoginRequiredMixin, View):
    def get(self, request, post_id):
        post = get_object_or_404(Post, pk=post_id)
        like = Like.objects.filter(post=post, user=request.user)
        if like.exists():
            messages.error(request, 'You have already liked this post!', 'danger')
        else:
            like.create(post=post, user=request.user)
            messages.success(request, 'You liked this post', 'success')
        return redirect('home:post_detail', post.id, post.slug)


class PostDislikeView(LoginRequiredMixin, View):
    def get(self, request, post_id):
        post = get_object_or_404(Post, pk=post_id)
        like = Like.objects.filter(post=post, user=request.user)
        if like.exists():
            like.delete()
            messages.warning(request, 'you dislike this post ', 'warning')
        else:
            messages.error(request, 'You don\'t like this post', 'danger')
        return redirect('home:post_detail', post.id, post.slug)

home/templates/home/create.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}
    Post Create
{% endblock %}

{% block content %}
    <form action="" method="POST" novalidate>
    {% csrf_token %}
    {{ form|crispy }}
        <input type="submit" value="Create" class="btn btn-info">

    </form>
{% endblock %}

home/templates/home/detail.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}
    Post Detail
{% endblock %}

{% block content %}
    <div class="card">
        <div class="card-body">
            <h3>{{ post.title }}</h3>
            <small>by: <a href="{% url 'account:user_profile' post.user.id %}">{{ post.user.username }}</a></small><br>
            <small>{{ post.modified|date:"Y-m-D-P" }}</small>
            <p>{{ post.body }}</p>
            {% if request.user.is_authenticated %}
                {% if not user_cant_like %}
                    <a href="{% url 'home:post_like' post.id %}" class="btn btn-outline-danger">
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                             class="bi bi-heart" viewBox="0 0 16 16">
                            <path d="m8 2.748-.717-.737C5.6.281 2.514.878 1.4 3.053c-.523 1.023-.641 2.5.314 4.385.92 1.815 2.834 3.989 6.286 6.357 3.452-2.368 5.365-4.542 6.286-6.357.955-1.886.838-3.362.314-4.385C13.486.878 10.4.28 8.717 2.01L8 2.748zM8 15C-7.333 4.868 3.279-3.04 7.824 1.143c.06.055.119.112.176.171a3.12 3.12 0 0 1 .176-.17C12.72-3.042 23.333 4.867 8 15z"></path>
                        </svg>
                        Like{{ post.likes_count }}
                    </a>
                {% endif %}
                {% if user_cant_like %}
                    <a href="{% url 'home:post_dislike' post.id %}" class="btn btn-outline-warning">
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                             class="bi bi-heart" viewBox="0 0 16 16">
                            <path d="m8 2.748-.717-.737C5.6.281 2.514.878 1.4 3.053c-.523 1.023-.641 2.5.314 4.385.92 1.815 2.834 3.989 6.286 6.357 3.452-2.368 5.365-4.542 6.286-6.357.955-1.886.838-3.362.314-4.385C13.486.878 10.4.28 8.717 2.01L8 2.748zM8 15C-7.333 4.868 3.279-3.04 7.824 1.143c.06.055.119.112.176.171a3.12 3.12 0 0 1 .176-.17C12.72-3.042 23.333 4.867 8 15z"></path>
                        </svg>
                        Dislike{{ post.likes_count }}
                    </a>
                {% endif %}
            {% endif %}
            {% if request.user.id == post.user.id %}
                <a href="{% url 'home:post_delete' post.id %}" class="btn btn-danger">Delete</a>
                <a href="{% url 'home:post_update' post.id %}" class="btn btn-info">Update</a>
            {% endif %}

        </div>
    </div>
    <div>
        <br>
        {% if request.user.is_authenticated %}
            <form action="" method="post">
                {% csrf_token %}
                {{ form|crispy }}
                <br>
                <input class="btn btn-primary" type="submit" value="Send">
            </form>
        {% else %}
            <p class="alert alert-danger">Only logged in users can comment!</p>
        {% endif %}
    </div><br>

    {% for comment in comments %}
        <div class="card bg-dark text-white">
            <p class="card-header">{{ comment.user.username }} | {{ comment.created|timesince }} </p>
            <p class="card-body">{{ comment.body }}</p>
            {% if request.user.is_authenticated %}
                <form action="{% url 'home:add_reply' post.id comment.id %}" method="post">
                    {% csrf_token %}
                    {{ reply_form|crispy }}
                    <input class="btn btn-primary" type="submit" value="Reply">
                </form><br>

            {% endif %}
            {% with replies=comment.rcomments.all %}
                {% for reply in replies %}
                    <p class="bg-primary p-3 m-2">{{ reply.user }} <br> {{ reply.body }}</p>
                {% endfor %}
            {% endwith %}

        </div><br>
    {% empty %}
        <div class="card bg-dark text-white">
            <p class="card-header">No comments yet!</p>
        </div>
    {% endfor %}




{% endblock %}

home/templates/home/index.html
{% extends 'base.html' %}

{% block title %}
    Index
{% endblock %}

{% block content %}

    <form class="col-md-2" action="" method="get">
        {{form}}
        <input class="btn btn-primary" type="submit" value="Search">

    </form>
    <br>

    <div class="card">
        {% for post in posts %}
            <h3><a href="{{ post.get_absolute_url }}" class="card-body">{{ post.title }}</a></h3>
        {% endfor %}
    </div>

{% endblock %}

home/templates/home/update.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}
    Post Update
{% endblock %}

{% block content %}
    <form action="" method="POST" novalidate>
    {% csrf_token %}
    {{ form|crispy }}
        <input type="submit" value="Update" class="btn btn-info">

    </form>
{% endblock %}